{"name": "test_check_for_local_user_region", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = contacts_section_rg_is_correct(<selenium.webdriver.chrome.webdriver.WebDriver (session=\"66e4acbbe8c24edd9f00bbe4e87918bf\")>)\n +    where contacts_section_rg_is_correct = <pages.contacts.Contacts object at 0x00000224CA9EAD50>.contacts_section_rg_is_correct", "trace": "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"66e4acbbe8c24edd9f00bbe4e87918bf\")>\n\n    @allure.feature('Contacts page, correct user region displayed, able to switch it')\n    @allure.story('UX')\n    def test_check_for_local_user_region(browser):\n        contacts_page = Contacts(browser)\n        contacts_page.open()\n    \n        with allure.step('Check that contacts button-link is displayed'):\n            assert contacts_page.contacts_section_change_rg_button_link_is_displayed\n        with allure.step('Check that rg is correct'):\n>           assert contacts_page.contacts_section_rg_is_correct(browser)\nE           assert False\nE            +  where False = contacts_section_rg_is_correct(<selenium.webdriver.chrome.webdriver.WebDriver (session=\"66e4acbbe8c24edd9f00bbe4e87918bf\")>)\nE            +    where contacts_section_rg_is_correct = <pages.contacts.Contacts object at 0x00000224CA9EAD50>.contacts_section_rg_is_correct\n\ntests\\test_second_scenario.py:14: AssertionError"}, "steps": [{"name": "Open page: https://saby.ru/contacts/77-moskva?tab=clients", "status": "passed", "start": 1750602514649, "stop": 1750602515252}, {"name": "Check that contacts button-link is displayed", "status": "passed", "start": 1750602515252, "stop": 1750602515252}, {"name": "Check that rg is correct", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = contacts_section_rg_is_correct(<selenium.webdriver.chrome.webdriver.WebDriver (session=\"66e4acbbe8c24edd9f00bbe4e87918bf\")>)\n +    where contacts_section_rg_is_correct = <pages.contacts.Contacts object at 0x00000224CA9EAD50>.contacts_section_rg_is_correct\n", "trace": "  File \"C:\\Users\\mark\\PycharmProjects\\test_tenzor\\tests\\test_second_scenario.py\", line 14, in test_check_for_local_user_region\n    assert contacts_page.contacts_section_rg_is_correct(browser)\n"}, "start": 1750602515252, "stop": 1750602516569}], "attachments": [{"name": "Screenshot on failure", "source": "4a913444-942a-4dad-ae11-ea82de76c22e-attachment.png", "type": "image/png"}], "start": 1750602514649, "stop": 1750602516570, "uuid": "02d38955-ad95-4fee-9228-3651805cdc22", "historyId": "4e7abf174d87d251f4a4894e9c1f11d0", "testCaseId": "4e7abf174d87d251f4a4894e9c1f11d0", "fullName": "tests.test_second_scenario#test_check_for_local_user_region", "labels": [{"name": "feature", "value": "Contacts page, correct user region displayed, able to switch it"}, {"name": "story", "value": "UX"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_second_scenario"}, {"name": "host", "value": "DESKTOP-KHTU12F"}, {"name": "thread", "value": "3356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_second_scenario"}]}